name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docs with sphinx
        run: |
          pip install -r docs/requirements.txt
          sphinx-build docs docs/_build
